# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hit',
            unique_together=set([('page', 'first_word_id')]),
        ),
    ]
