# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.IntegerField(unique=True)),
                ('type', models.IntegerField(blank=True, choices=[(1, 'Person'), (2, 'Geographic Place'), (3, 'Work'), (4, 'Organization'), (5, 'Meeting'), (200, 'Other')], null=True)),
                ('aliases', models.TextField(blank=True, null=True)),
                ('hebrew_alias', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
