# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='wikipedia_article',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='wikipedia_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
